import "./globals.css";
import { montserrat } from "@/lib/fonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={montserrat.className}>
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
